name: Suggestion
description: Suggest a cheat or script
title: "IDEA: Script idea name"
labels: ["enhancement"]
body:
  - type: input
    id: gamemode
    attributes:
      label: Gamemode
      description: Gamemode for cheat to be for
      placeholder: Gamemode
  - type: textarea
    id: function
    attributes:
      label: Function
      description: What does the script do?
      placeholder: Script function
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: Method
      description: Please make sure to read [the faq](https://github.com/Minesraft2/Blooket-Cheats/wiki#faq) before submitting any suggestions
      options:
        - I read the [faq questions](https://github.com/Minesraft2/Blooket-Cheats/wiki#faq) and my suggestion has not already been asked for or isn't possible
    validations:
      required: true