name: Bug report
description: Report an issue or problem with a script
title: "BUG: Script name"
labels: ["bug"]
assignees:
  - Minesraft2
body:
  - type: input
    id: script
    attributes:
      label: Script
      description: Which script is causing the problem?
      placeholder: scriptname.js
    validations:
      required: true
  - type: input
    id: problem
    attributes:
      label: Problem
      description: What's the problem with the script?
      placeholder: Describe the issue
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Method
      description: How did you run the script?
      options:
      - label: Imported Bookmarklets.html
      - label: "Put 'javascript:(code)' in the url bar"
      - label: Pasted script into console
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra Info
      description: Any extra info (ie screenshots or any important info)
    validations:
      required: false
